### PR TITLE
filter on a deprecation and adding a prefix

### PR DESCRIPTION
**Pull request by dougli1sqrd**
Added a missing prefix (obo) and filtering out deprecated classes for missing labels. :)

### CODE REVIEW

**Comment by beckyjackson** [comment]
There is discussion in #383 on deprecated entities in the report queries. Any input there is appreciated, but I'm going to hold off on making any changes to if deprecated entities are included or not in this branch. Thanks!

**Comment by dougli1sqrd** [comment]
What about the obo prefix in deprecated_class_reference.rq at least? Thanks!

**Comment by beckyjackson** [comment]
I had added it in 4fe8149

**Comment by dougli1sqrd** [comment]
Ha you're much faster than me on here. I was just coming back to say I see you already added it. Cool!

**Pull request closed without merging**
